name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          # GCC versions with different C++ standards
          #          - { name: gcc, version: "9", standard: "17" }
          #          - { name: gcc, version: "10", standard: "17" }
          #          - { name: gcc, version: "11", standard: "17" }
          #          - { name: gcc, version: "12", standard: "20" } # Test C++20
          #          - { name: gcc, version: "13", standard: "23" } # Test C++23
          - { name: gcc, version: "14", standard: "17" }
          # Clang versions with different C++ standards
          #          - { name: clang, version: "11", standard: "17" }
          #          - { name: clang, version: "12", standard: "20" } # Test C++20
          #          - { name: clang, version: "13", standard: "23" } # Test C++23
          #          - { name: clang, version: "14", standard: "17" }
          #          - { name: clang, version: "15", standard: "20" } # Test C++20
          #          - { name: clang, version: "16", standard: "23" } # Test C++23
          #          - { name: clang, version: "17", standard: "17" }
          #          - { name: clang, version: "18", standard: "20" } # Test C++20
          - { name: clang, version: "19", standard: "17" }

    container:
      image: ${{ matrix.config.name == 'gcc' && 'gcc:' || 'teeks99/clang-ubuntu:' }}${{ matrix.config.version }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup CMake
      uses: lukka/get-cmake@latest
      with:
        cmake-version: '3.25.0'

    - name: Validate Tools in Container
      run: |
        cmake --version
        make --version
        ${{ matrix.config.name }} --version
        ${{ matrix.config.name }}++ --version

    - name: Cache CMake Build
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ runner.os }}-cmake-${{ matrix.config.name }}-${{ matrix.config.version }}-${{ matrix.config.standard }}
        restore-keys: |
          ${{ runner.os }}-cmake-

    - name: Configure CMake
      run: |
        cmake -S . -B build \
          -DCMAKE_C_COMPILER=${{ matrix.config.name }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.config.name }}++ \
          -DCMAKE_CXX_STANDARD=${{ matrix.config.standard }}

    - name: Build
      run: cmake --build build

    - name: Test
      run: ./build/test_funkypipes
